### ISSUE TITLE
chai is not defined

### ISSUE THREAD

**Issue by bigsapper** [sitepoint-editors/mocha-unit-testing#1]
Hi, I'm trying to setup a testing framework and came across your article for this repo. I kept getting the above error, so I cloned your repo, npm install, npm test and still get this error. Mac OS High Sierra. I'm sure I'm missing something simple.

And to clarify, this is using the testrunner.html.

**Comment by jameshibbard** [comment]
Hi, 

you need to uncomment the Node specific code in `className.js`, `arrayTest.js` and `classNameTest.js` then things will work as expected.

**Comment by bigsapper** [comment]
It's not a node app. The tutorial specifically has a setup for testing as a browser app. In any case, my conundrum seems to be rooted in "npm test" is a node-based testing framework. When I configured my project to serve the testrunner.html page to the node server, it executed appropriately.
